version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    restart: always
    environment:
      - APPLE_ID
      - PASSWORD
      - PORT
      - HOST
    ports:
      - 3000:3000
